services:
  openldap:
    image: bitnami/openldap:2
    container_name: openldap
    platform: linux/amd64
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: adminpassword
    networks:
      - ldap-network
    volumes:
      - openldap_data:/bitnami/openldap

  freeipa:
    image: freeipa/freeipa-server:rocky-9
    container_name: freeipa-server
    platform: linux/amd64
    hostname: ipa.example.com
    privileged: true
    ports:
      - "1388:389"    # LDAP
      - "1637:636"    # LDAPS
      - "1088:88"     # Kerberos
      - "1464:464"    # Kerberos kpasswd
      - "1053:53/udp" # DNS (optional)
      - "1080:80"     # HTTP
      - "1443:443"    # HTTPS
    environment:
      IPA_SERVER_HOSTNAME: ipa.example.com
      PASSWORD: "admin1234"  # Admin password for FreeIPA
      REALM: "EXAMPLE.COM"   # Kerberos realm
      DOMAIN: "example.com"  # Domain
      TZ: "UTC"              # Timezone
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./freeipa_data:/data:Z
      command:
      - -U
      - --realm=EXAMPLE.COM
      - --domain=example.com
      - --ds-password=admin1234
      - --admin-password=admin1234
      - --hostname=ipa.example.com
      - --unattended
      - --skip-mem-check
      - --allow-zone-overlap
      - --no-host-dns
      - --no-dns
    networks:
      - ldap-network

  jboss-keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    image: jboss-eap:8.0
    container_name: jboss-keycloak
    platform: linux/amd64
    ports:
      - "8080:8080" # JBoss http
      - "9990:9990" # JBoss Admin
      - "8543:8543" # Keycloak https
    networks:
      - ldap-network
    depends_on:
      - openldap


  rhel8:
    image: registry.access.redhat.com/ubi8/ubi
    platform: linux/amd64
    container_name: rhel8
    ports:
      - "8081:8080"
      - "8082:80"
    volumes:
      - "./add-email.ldif:/add-email.ldif" 
      - "./rhelInit.sh:/rhelInit.sh"
    networks:
      - ldap-network
    command: ["/bin/bash", "/rhelInit.sh"]

networks:
  ldap-network:
    driver: bridge

volumes:
  openldap_data:
    driver: local
  freeipa_data:


